# Generated by Django 3.0 on 2024-03-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                # Rename existing table to new app's table name
                migrations.RunSQL(
                    "ALTER TABLE oc_lettings_site_profile RENAME TO profiles_profile;",
                    reverse_sql="ALTER TABLE profiles_profile RENAME TO oc_lettings_site_profile;",
                ),
            ],
        ),
    ]
