# Generated by Django 3.0 on 2024-03-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                # Rename existing tables to new app's table names
                migrations.RunSQL(
                    "ALTER TABLE oc_lettings_site_address RENAME TO lettings_address;",
                    reverse_sql="ALTER TABLE lettings_address RENAME TO oc_lettings_site_address;",
                ),
                migrations.RunSQL(
                    "ALTER TABLE oc_lettings_site_letting RENAME TO lettings_letting;",
                    reverse_sql="ALTER TABLE lettings_letting RENAME TO oc_lettings_site_letting;",
                ),
            ],
        ),
    ]
