# Generated by Django 3.0 on 2024-03-15 18:06

from django.db import migrations


def transfer_data_forward(apps, schema_editor):
    """Transfer data from old tables to new apps"""
    # Note: The data is already in the correct tables after rename operations
    # This migration serves as a data verification step
    Address = apps.get_model('lettings', 'Address')
    Letting = apps.get_model('lettings', 'Letting')
    
    # Verify data exists
    address_count = Address.objects.count()
    letting_count = Letting.objects.count()
    
    print(f"Lettings data verification: {address_count} addresses, {letting_count} lettings")


def transfer_data_reverse(apps, schema_editor):
    """Reverse data transfer if needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_rename_tables'),
    ]

    operations = [
        migrations.RunPython(transfer_data_forward, transfer_data_reverse),
    ]
