name: CD - Build and Deploy

on:
  workflow_run:
    workflows: ["CI - Test and Lint"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC
  # This workflow runs after the CI workflow completes successfully,

jobs:
  build-and-push:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      # uses: docker/login-action@v2
      # with:
      #   username: ${{ secrets.DOCKER_USERNAME }}
      #   password: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "Docker login is skipped for this run."

    - name: Extract commit hash
      # id: vars
      # run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      run: echo "Commit hash extraction is skipped for this run."
      
    - name: Build and push
      # uses: docker/build-push-action@v4
      # with:
      #   context: .
      #   push: true
      #   tags: |
      #     ${{ secrets.DOCKER_USERNAME }}/ocr_django-lettings:latest
      #     ${{ secrets.DOCKER_USERNAME }}/ocr_django-lettings:${{ steps.vars.outputs.sha_short }}
      run: echo "Docker build and push is skipped for this run."
          
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Extract commit hash
      id: vars
      # run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      run: echo "Commit hash extraction is skipped for this run."
      
    - name: Set up SSH
      # run: |
      #   mkdir -p ~/.ssh
      #   echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #   chmod 600 ~/.ssh/id_rsa
      #   ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      run: echo "SSH setup is skipped for this run."

    - name: Deploy to server
      # run: |
      #   ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
      #     docker pull ${{ secrets.DOCKER_USERNAME }}/ocr_django-lettings:${{ steps.vars.outputs.sha_short }}
      #     docker stop django-lettings || true
      #     docker rm django-lettings || true
      #     docker run -d --name django-lettings \
      #       -p 8000:8000 \
      #       -e SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}' \
      #       -e SENTRY_DSN='${{ secrets.SENTRY_DSN }}' \
      #       -e DEBUG=False \
      #       ${{ secrets.DOCKER_USERNAME }}/ocr_django-lettings:${{ steps.vars.outputs.sha_short }}
      #   "
      run: echo "Deployment to server is skipped for this run."
        
    - name: Verify deployment
      # run: |
      #   sleep 10
      #   curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.SERVER_HOST }}:8000/ | grep 200
      run: echo "Deployment verification is skipped for this run."
